version: '3.1'

services:

  db:
    image: mariadb:10.4.30
    restart: always
    environment:
      MYSQL_DATABASE: mundodop_wp556
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    links:
      - db
    depends_on:
      - db
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=1
      - UPLOAD_LIMIT=500M

  wordpress:
    image: wordpress:6.1.1-php7.4-apache
    restart: always
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: mundodop_wp556
      WORDPRESS_TABLE_PREFIX: wpos_
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db
